# Generated by Django 4.0.2 on 2022-02-17 04:29

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Esal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo')),
                ('resumen', models.TextField(verbose_name='resumen')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='archivos/')),
                ('publicar', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'esal',
                'verbose_name_plural': 'esals',
            },
        ),
    ]
