# Generated by Django 4.0.2 on 2022-04-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esal', '0004_alter_esal_vigencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esal',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='archivos/esal/%Y/%m/%d'),
        ),
    ]
