# Generated by Django 4.0.2 on 2022-03-18 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='ocupation',
            field=models.CharField(blank=True, choices=[('0', 'Administrador'), ('1', 'Secretario/a'), ('2', 'Tesorero'), ('3', 'Gerente'), ('4', 'Junta')], max_length=1),
        ),
    ]
